# Generated by Django 4.2.23 on 2025-07-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.BigIntegerField(default=0)),
                ('email', models.EmailField(max_length=150)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='tipoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='tipoQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default='')),
                ('noites', models.IntegerField(default='')),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotelaria.hospede')),
                ('servico', models.ManyToManyField(blank=True, related_name='serviços', to='hotelaria.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('andar', models.IntegerField()),
                ('status', models.CharField(max_length=45)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descricao', models.CharField(max_length=90)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='hotelaria.reserva')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quartos', to='hotelaria.tipoquarto')),
            ],
        ),
        migrations.CreateModel(
            name='pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default='', max_digits=8)),
                ('data', models.DateField(default='')),
                ('forma', models.CharField(max_length=20)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotelaria.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('cpf', models.IntegerField()),
                ('sexo', models.CharField(max_length=30)),
                ('servico', models.ManyToManyField(blank=True, related_name='funcionários', to='hotelaria.servico')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionários', to='hotelaria.tipofuncionario')),
            ],
        ),
    ]
