# Generated by Django 4.2.23 on 2025-07-03 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotelaria.hospede')),
            ],
        ),
        migrations.CreateModel(
            name='pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=20)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotelaria.reserva')),
            ],
        ),
    ]
