# Generated by Django 4.2.23 on 2025-07-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelaria', '0002_reserva_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='data',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
