# Generated by Django 4.2.23 on 2025-07-03 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelaria', '0002_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('andar', models.IntegerField()),
                ('status', models.CharField(max_length=45)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descricao', models.CharField(max_length=90)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quartos', to='hotelaria.tipoquarto')),
            ],
        ),
    ]
