# Generated by Django 4.2.23 on 2025-07-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelaria', '0003_pagamento_data_reserva_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateField(default=models.DateField(auto_now=True)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(default=models.DateField(auto_now=True)),
        ),
    ]
