# Generated by Django 4.2.23 on 2025-07-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelaria', '0005_reserva_noites_alter_pagamento_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(default=2025),
        ),
    ]
