# Generated by Django 4.2.23 on 2025-07-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelaria', '0006_alter_reserva_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospede',
            name='cpf',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateField(default=2025),
        ),
    ]
