# Generated by Django 4.2.23 on 2025-07-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelaria', '0007_hospede_cpf_alter_pagamento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospede',
            name='cpf',
            field=models.BigIntegerField(default=1),
        ),
    ]
