# Generated by Django 4.2.23 on 2025-07-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelaria', '0008_alter_hospede_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
        ),
    ]
