# Generated by Django 4.2.23 on 2025-07-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelaria', '0009_pagamento_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='noites',
            field=models.IntegerField(default=''),
        ),
    ]
