# Generated by Django 4.2.23 on 2025-07-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelaria', '0003_tipoquarto_quarto'),
        ('hotelaria', '0010_alter_pagamento_data_alter_pagamento_valor_and_more'),
    ]

    operations = [
    ]
