# Generated by Django 4.2.23 on 2025-07-04 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelaria', '0011_merge_20250704_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='hotelaria.reserva'),
        ),
    ]
