# Generated by Django 4.2.23 on 2025-07-04 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelaria', '0012_quarto_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hotelaria.servico'),
        ),
    ]
