# Generated by Django 4.2.23 on 2025-07-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelaria', '0013_reserva_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='servico',
        ),
        migrations.AddField(
            model_name='reserva',
            name='servico',
            field=models.ManyToManyField(blank=True, null=True, related_name='serviços', to='hotelaria.servico'),
        ),
    ]
